services:
  costellobot:
    image: ${DOCKER_REGISTRY-}costellobot:latest
    depends_on:
      - servicebus-emulator
    ports:
      - '8080:8080'
    environment:
      - ConnectionStrings__AzureServiceBus=Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ConnectionStrings__AzureTableStorage=UseDevelopmentStorage=true
      - DOTNET_ENVIRONMENT=Production
      - GitHub__ClientId=github-client-id
      - GitHub__ClientSecret=github-client-secret
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - Webhook__QueueName=queue.1
      - WEBSITE_SITE_NAME=Costellobot
  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:1.1.2@sha256:353913ece3d9124cebd40f4b91d00dd197846b8cf86eae9a4790698709c64a1d
    depends_on:
      - sql-server
    ports:
      - '5300:5300'
      - '5672:5672'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=C0st3ll0b0t$
      - SQL_SERVER=sql-server:1433
  sql-server:
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:54b23ca766287dab5f6f55162923325f07cdec6ccb42108f37c55c87e7688ebd
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=C0st3ll0b0t$
