services:
  costellobot:
    image: ${DOCKER_REGISTRY-}costellobot:latest
    depends_on:
      - servicebus-emulator
    ports:
      - '8080:8080'
    environment:
      - ConnectionStrings__AzureServiceBus=Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
      - ConnectionStrings__AzureTableStorage=UseDevelopmentStorage=true
      - DOTNET_ENVIRONMENT=Production
      - GitHub__ClientId=github-client-id
      - GitHub__ClientSecret=github-client-secret
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - Webhook__QueueName=queue.1
      - WEBSITE_SITE_NAME=Costellobot
  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:2.0.0@sha256:a00c9626c8960f6b9be6178aa91a7ac8f1a102c0d9deda7603a1ba0ac9d9ab51
    depends_on:
      - sql-server
    ports:
      - '5300:5300'
      - '5672:5672'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=C0st3ll0b0t$
      - SQL_SERVER=sql-server:1433
  sql-server:
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:698682bab57c02c42bc0aa274b158aeb242d8e9104149a7489628d5535805816
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=C0st3ll0b0t$
